swagger: "2.0"
info:
  title: PEARMONIE LLC API DOCUMENTATION
  description: Content recommendation API Documentation
  version: 1.0
  contact:
    email: onojamatthew59@gmail.com
  license:
    name: MIT
    url: "http://mit.com/"
  servers:
    - url: http://localhost:5000
      description: This is my local server
    - url: http://35.179.111.36
      description: This is LIVE server 
schemes: [http, https]
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >-
      Enter the token with the `Bearer: ` prefix, e.g. "Bearer eyhde12345"
paths:
  /health:
    get:
      tags:
        - HEALTH CHECK
      summary: SERVER HEALTH CHECK
      description: CHECKS THE HEALTH STATUS OF THE SERVER
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                default: Status OK!

  /api/v1/auth/register:
    get:
      tags:
        - AUTH
      summary: BUSINESS REGISTRATION API
      description: CREATE BUSINESS ACCOUNT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          type: object
          name: requestBody
        
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              message: 
                type: string
                default: Request processed
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      default: 1
                    name:
                      type: string
                      default: admin
                    createdBy:
                      type: object
                      properties:
                        firstName:
                          type: string
                          default: John
                        lastName:
                          type: string
                          default: Doe
                        fullName:
                          type: string
                          default: John Doe
                        id:
                          type: number
                          default: 1
                    deleted:
                      type: boolean
                      default: false
                    createdAt:
                      type: date
                      default: 2025-03-18 18:18:50
                    updatedAt:
                      type: date
                      default: 2025-03-18 18:18:50

  /api/v1/roles/new:
    post:
      security:
        - Bearer: []
      tags:
        - ROLES
      summary: NEW ROLE
      description: CREATES A NEW ROLE
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requestBody
          type: object
          schema:
            properties:
              name:
                type: string
                default: admin
                required: true
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              message: 
                type: string
                default: Role created
              data:
                type: object
                properties:
                  id:
                    type: number
                    default: 1
                  name:
                    type: string
                    default: admin
                  createdBy:
                    type: object
                    properties:
                      firstName:
                        type: string
                        default: John
                      lastName:
                        type: string
                        default: Doe
                      fullName:
                        type: string
                        default: John Doe
                      id:
                        type: number
                        default: 1
                  deleted:
                    type: boolean
                    default: false
                  createdAt:
                    type: date
                    default: 2025-03-18 18:18:50
                  updatedAt:
                    type: date
                    default: 2025-03-18 18:18:50
