swagger: "2.0"
info:
  title: PEARMONIE LLC API DOCUMENTATION
  description: Content recommendation API Documentation
  version: 1.0
  contact:
    email: onojamatthew59@gmail.com
  license:
    name: MIT
    url: "http://mit.com/"
  servers:
    - url: http://localhost:5000
      description: This is my local server
    - url: http://localhost:5000
      description: This is LIVE server 
schemes: [http, https]
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >-
      Enter the token with the `Bearer: ` prefix, e.g. "Bearer eyhde12345"
paths:
  /health:
    get:
      tags:
        - HEALTH CHECK
      summary: SERVER HEALTH CHECK
      description: CHECKS THE HEALTH STATUS OF THE SERVER
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                default: Status OK!



  /api/v1/auth/business/register:
    post:
      tags:
        - AUTH
      summary: BUSINESS REGISTERATION
      description: ENDPOINT FOR BUSINESS REGISTERATION
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requestBody
          type: object
          schema:
            properties:
              name:
                type: string
                default: Olarewaju Ayodele
                required: true
              businessName:
                type: string
                default: ola enterprise
                required: true
              email:
                type: string
                default: ola@gmail.com
                required: true
              password:
                type: string
                default: password@123
                required: true
              role:
                type: string
                default: content_manager
                required: true
      responses:
        200:
          description: Success
          schema:
            properties:
              success:
                type: boolean
                default: true
              message:
                type: string
                default: Registration successful
              data:
                type: object
                properties:
                  name:
                    type: string
                    default: Olarewaju Ayodele
                  businessName:
                    type: string
                    default: ola enterprise
                  email:
                    type: string
                    default: ola@gmail.com
                    required: true
                  role:
                    type: string
                    default: content_manager
                  businessId:
                    type: string
                    default: 6824a9af4b8e81f4af4c12aa
                  token:
                    type: string
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmYzYTczMjAzZDZiNTBmNmEyZWQ4ZSIsImJ1c2luZXNzSWQiOiI2ODJmM2E3MzIwM2Q2YjUwZjZhMmVkOGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzkyNTYxOSwiZXhwIjoxNzUwNTE3NjE5fQ.Bv2jd-KQkB4eFPFxKx0k5RB1IItFWH56j1tNPsaneII
                  createdAt:
                    type: date
                    default: 2025-03-18 18:18:50
                  updatedAt:
                    type: date
                    default: 2025-03-18 18:18:50  
  
  /api/v1/auth/business/login:
    post:
      tags:
        - AUTH
      summary: BUSINESS REGISTERATION
      description: ENDPOINT FOR BUSINESS REGISTERATION
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requestBody
          type: object
          schema:
            properties:
              email:
                type: string
                default: ola@gmail.com
                required: true
              password:
                type: string
                default: password@123
                required: true
      responses:
        200:
          description: Success
          schema:
            properties:
              success:
                type: boolean
                default: true
              message:
                type: string
                default: Registration successful
              data:
                type: object
                properties:
                  name:
                    type: string
                    default: Olarewaju Ayodele
                  businessName:
                    type: string
                    default: ola enterprise
                  email:
                    type: string
                    default: ola@gmail.com
                    required: true
                  role:
                    type: string
                    default: content_manager
                  businessId:
                    type: string
                    default: 6824a9af4b8e81f4af4c12aa
                  token:
                    type: string
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmYzYTczMjAzZDZiNTBmNmEyZWQ4ZSIsImJ1c2luZXNzSWQiOiI2ODJmM2E3MzIwM2Q2YjUwZjZhMmVkOGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzkyNTYxOSwiZXhwIjoxNzUwNTE3NjE5fQ.Bv2jd-KQkB4eFPFxKx0k5RB1IItFWH56j1tNPsaneII
                  createdAt:
                    type: date
                    default: 2025-03-18 18:18:50
                  updatedAt:
                    type: date
                    default: 2025-03-18 18:18:50  

  /api/v1/auth/user/register:
    post:
      tags:
        - AUTH
      summary: BUSINESS REGISTERATION
      description: ENDPOINT FOR BUSINESS REGISTERATION
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requestBody
          type: object
          schema:
            properties:
              email:
                type: string
                default: ola@gmail.com
                required: true
              password:
                type: string
                default: password@123
                required: true
      responses:
        200:
          description: Success
          schema:
            properties:
              success:
                type: boolean
                default: true
              message:
                type: string
                default: Registration successful
              data:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
                    default:
                  email:
                    type: string
                    default: ola@gmail.com
                    required: true
                  role:
                    type: string
                    default: content_manager
                  businessName:
                    type: string
                    default: ola enterprise
                  token:
                    type: string
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmYzYTczMjAzZDZiNTBmNmEyZWQ4ZSIsImJ1c2luZXNzSWQiOiI2ODJmM2E3MzIwM2Q2YjUwZjZhMmVkOGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzkyNTYxOSwiZXhwIjoxNzUwNTE3NjE5fQ.Bv2jd-KQkB4eFPFxKx0k5RB1IItFWH56j1tNPsaneII
                  id:
                    type: string
                    default: 67ca0f97c349084e38bbf0aa
                  createdAt:
                      type: date
                      default: 2025-03-18 18:18:50
                  updatedAt:
                    type: date
                    default: 2025-03-18 18:18:50

  /api/v1/contents:
    post:
      tags:
        - CONTENT
      summary: CREATE
      description: CREATES BOOK CONTENT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requestBody
          type: object
          schema:
            properties:
              title:
                type: string
                default: Why do we use it?
                required: true
              textContent:
                type: string
                default: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
              genre:
                type: string
                default: fiction
                required: true
              author:
                type: string
                default: Igoche Ogbanje
                required: true
              url:
                type: string
                default: https://picsum.photos/200/300
      responses:
        200:
          description: Success
          schema:
            properties:
              success:
                type: boolean
                default: true
              message:
                type: string
                default: 
              data:
                type: object
                properties:
                  title:
                    type: string
                    default: Why do we use it?
                    required: true
                  textContent:
                    type: string
                    default: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                  genre:
                    type: string
                    default: fiction
                    required: true
                  author:
                    type: string
                    default: Igoche Ogbanje
                    required: true
                  url:
                    type: string
                    default: https://picsum.photos/200/300
                  id:
                    type: string
                    default: 67ca0f97c349084e38bbf0aa
                  createdAt:
                      type: date
                      default: 2025-03-18 18:18:50
                  updatedAt:
                    type: date
                    default: 2025-03-18 18:18:50
  